[package]
name = "wg-toolkit"
version = "0.1.1"
authors = ["Théo Rozier <contact@theorozier.fr>"]
edition = "2021"
license = "GPL-3.0"
description = "Toolkit for various binary and text formats distributed by Wargaming.net (BigWorld, Core engine)."
categories = ["games", "parsing", "data-structures"]

[dependencies]
byteorder = "1.4.3"
xmltree = "0.10.3"
base64 = "0.13.0"

[lib]
name = "wgtk"
