[package]
name = "wg-toolkit"
version = "0.1.0"
edition = "2021"
description = "Toolkit for various binary and text formats distributed by Wargaming.net (BigWorld, Core engine)."

[dependencies]
byteorder = "1.4.3"
xmltree = "0.10.3"
base64 = "0.13.0"

[lib]
name = "wgtk"
