[package]
name = "wg-toolkit"
version = "0.1.0"
edition = "2021"
description = "Toolkit for various binary and text formats distributed by Wargaming.net (BigWorld, Core engine)."

[dependencies]
byteorder = "1.4.3"

[lib]
name = "wgtk"
