[package]
name = "wg-toolkit"
version = "0.3.0"
authors = ["Théo Rozier <contact@theorozier.fr>"]
edition = "2021"
license = "MIT"
description = "Toolkit for various binary and text formats distributed by Wargaming.net (BigWorld, Core engine)."
categories = ["games", "parsing", "data-structures"]
homepage = "https://github.com/mindstorm38/wg-toolkit-rs"
repository = "https://github.com/mindstorm38/wg-toolkit-rs"
readme = "../README.md"

[dependencies]
byteorder = "1.4"
glam = "0.21"
smallvec = "1.10"
base64 = "0.13"
thiserror = "1.0"
zip = "0.6"
sha2 = { version = "0.10", optional = true }
sha1 = { version = "0.10", optional = true }
rsa = { version = "0.8", optional = true }
rand = { version = "0.8", optional = true }
mio = { version = "0.8", features = ["net", "os-poll"], optional = true }
blowfish = { version = "0.9", optional = true }
crypto-common = { version = "0.1", optional = true }

[features]
default = []
network = [
    "dep:mio", 
    "dep:sha1", 
    "dep:sha2", 
    "dep:rand", 
    "dep:rsa", 
    "dep:blowfish", 
    "dep:crypto-common"
]

[lib]
name = "wgtk"

[[example]]
name = "server"
required-features = ["network"]
